name: Scrape Jacobs Farming events

on:
  push:
    branches:
      - schedule

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install PolyMC
        run: /usr/bin/sudo apt-get install -y libqt5xml5 libqt5widgets5 libqt5gui5 && mkdir polymc && curl -sSfL https://github.com/PolyMC/PolyMC/releases/download/1.3.2/PolyMC-Linux-portable-1.3.2.tar.gz | tar xzf - -C polymc


      - name: Run polymc
        uses: GabrielBB/xvfb-action@v1
        with:
          run: bin/polymc --help
          working-directory: ./polymc/
